# Generated by Django 3.2.8 on 2022-01-17 10:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('colour', models.CharField(max_length=50)),
                ('sides', models.CharField(choices=[('D4', '4 Seiten'), ('D6', '6 Seiten'), ('D8', '8 Seiten'), ('D10', '10 Seiten'), ('D12', '12 Seiten'), ('D20', '20 Seiten')], max_length=3)),
                ('prize', models.FloatField(max_length=6)),
                ('image', models.ImageField(blank=True, null=True, upload_to='dice_pictures/')),
                ('product_info', models.FileField(blank=True, null=True, upload_to='dice_info/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_created_by', related_query_name='book_created_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
