# Generated by Django 4.0 on 2022-01-24 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('colour', models.CharField(max_length=50)),
                ('sides', models.CharField(choices=[('D4', '4 Seiten'), ('D6', '6 Seiten'), ('D8', '8 Seiten'), ('D10', '10 Seiten'), ('D12', '12 Seiten'), ('D20', '20 Seiten')], max_length=3)),
                ('prize', models.FloatField(max_length=6)),
                ('image', models.ImageField(blank=True, null=True, upload_to='dice_pictures/')),
                ('product_info', models.FileField(blank=True, null=True, upload_to='dice_info/')),
            ],
        ),
    ]
