# Generated by Django 4.0 on 2022-01-24 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Useradmin', '0001_initial'),
        ('Dices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dice',
            name='superuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_created_by', related_query_name='product_created_by', to='Useradmin.shopuser'),
        ),
    ]
