# Generated by Django 4.0 on 2021-12-27 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dice',
            name='product_info',
            field=models.FileField(blank=True, null=True, upload_to='dice_info/'),
        ),
    ]
