# Generated by Django 3.2.8 on 2022-02-05 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dices', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dice',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
