# Generated by Django 4.0 on 2021-12-13 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Reviews', '0001_initial'),
        ('Useradmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('helpful_or_not', models.CharField(choices=[('H', 'Helpful'), ('N', 'Not Helpful')], max_length=1)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_created_for_review', related_query_name='vote_created_for_review', to='Reviews.review')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_created_by', related_query_name='vote_created_by', to='Useradmin.shopuser')),
            ],
            options={
                'verbose_name': 'Vote',
                'verbose_name_plural': 'Votes',
            },
        ),
    ]
