# Generated by Django 4.0 on 2021-12-27 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Votes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='helpful_or_not',
            field=models.CharField(choices=[('H', 'Helpful'), ('N', 'Not Helpful')], default='H', max_length=1),
        ),
    ]
