# Generated by Django 3.2.8 on 2022-01-10 12:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Dices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50)),
                ('text', models.CharField(max_length=1000)),
                ('rating', models.CharField(choices=[('1', 'ein Stern'), ('2', 'zwei Sterne'), ('3', 'drei Sterne'), ('4', 'vier Sterne'), ('5', 'fünf Sterne')], default='1', max_length=1)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('product_reviewed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dices.dice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
