# Generated by Django 3.2.8 on 2021-11-28 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Useradmin', '0003_auto_20211128_1310'),
        ('Reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Useradmin.shopuser'),
        ),
    ]
