# Generated by Django 4.0 on 2021-12-27 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Useradmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopuser',
            name='type',
            field=models.CharField(choices=[('SU', 'Superuser'), ('CS', 'Customerservice'), ('U', 'User')], default='U', max_length=2),
        ),
    ]
