# Generated by Django 4.0 on 2021-12-13 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Order', '0001_initial'),
        ('Useradmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_ordered_by', related_query_name='product_ordered_by', to='Useradmin.shopuser'),
        ),
    ]
