# Generated by Django 3.2.8 on 2021-11-28 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Useradmin', '0003_auto_20211128_1310'),
        ('Order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_ordered_by', related_query_name='product_ordered_by', to='Useradmin.shopuser'),
        ),
    ]
